# Generated by Django 5.0.5 on 2024-06-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalmetrics",
            name="appointments",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goalmetrics",
            name="assistance",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goalmetrics",
            name="monthly_goal_porcentage",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
