# Generated by Django 5.0.5 on 2024-06-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0002_goalmetrics_appointments_goalmetrics_assistance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalmetrics",
            name="monthly_goal_porcentage",
            field=models.FloatField(),
        ),
    ]
