# Generated by Django 5.0.5 on 2024-06-09 03:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0003_alter_goalmetrics_monthly_goal_porcentage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="apponitmentsGoal",
            new_name="apponitments_goal",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="endTime",
            new_name="end_time",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="startTime",
            new_name="start_time",
        ),
    ]
