# Generated by Django 5.0.5 on 2024-05-08 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("phone", models.CharField(blank=True, default="", max_length=25)),
                ("age", models.IntegerField()),
                (
                    "place",
                    models.CharField(
                        choices=[
                            ("CDO", "CDO"),
                            ("SEMILLERO", "Semillero"),
                            ("EXTERNAL", "Externo"),
                        ],
                        default="CDO",
                        max_length=50,
                    ),
                ),
                ("pacientNumber", models.IntegerField(blank=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("grade", models.TextField(blank=True, default="")),
                ("state", models.BooleanField()),
                ("stateDescription", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
