# Generated by Django 5.0.5 on 2024-06-09 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.TimeField()),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity_type", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DONE", "Hecho"),
                            ("PENDING", "Pendiente"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        choices=[
                            ("CDO", "CDO"),
                            ("SEMILLERO", "Semillero"),
                            ("OTHER", "Otro"),
                        ],
                        default="CDO",
                        max_length=50,
                    ),
                ),
                (
                    "doctors",
                    models.ManyToManyField(
                        related_name="activity", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
